### ISSUE TITLE
Track doesn't download, console output is clear

### ISSUE THREAD

**Issue by furagi** [scorpp/db-vk#35] opened 2016-06-07 16:19 UTC
Deadbeef output:
```
Requesting URL https://api.vk.com/method/audio.getById?access_token=*&audios=173040697_456239111
vk_vfs_store_track: https://cs5-3v4.vk-cdn.net/p23/264c5d2ea1021b.mp3?extra=WQph6AJDNlgX0yVj5LE75MnNDitoS_ZA9qYyL24HqQRxvl0Vgt__yztAHV2SEHk0-uBUkIwlvLLJOCo29em5mdku7aB_2frDwxNrrVbnWn20jQmEG9IKArt5W9Z3224807WaXsjde-GuGvbk, index=0
```
I tried to download file from link above (vk_vfs_store_track) via curl, everything is ok.
Deadbeef-vk (from overlay stuff):
```
[I] media-plugins/deadbeef-vk [1]
     Available versions:  ~0.1.13-r1 ~0.2.0 ~0.2.1 (~)0.2.2 **9999 {gtk2 gtk3}
     Installed versions:  0.2.2(01:52:35 08.06.2016)(gtk2 -gtk3)
 ```
Deadbeef:
```
[I] media-sound/deadbeef [1]
     Available versions:  (~)0.5.6-r4 (~)0.6.0-r1 (~)0.6.1 (~)0.6.2 (~)0.7.0 **9999-r8
     Installed versions:  0.7.0(01:52:15 08.06.2016)(aac alac alsa ape cdda converter curl dts dumb ffmpeg flac gtk2 hotkeys m3u mp3 musepack nls pulseaudio vorbis wavpack wma -adplug -cover -cover-imlib2 -gme -gtk3 -lastfm -midi -mms -mono2stereo -notify -nullout -oss -pltbrowser -psf -rpath -shellexec -shn -sid -sndfile -src -static -supereq -threads -tta -vtx -zip)
 ```
Curl:
```
[I] net-misc/curl
     Available versions:  7.45.0^t ~7.47.1^t 7.49.0^t
     Installed versions:  7.49.0^t(02:11:22 08.06.2016)(ldap ssl -adns -http2 -idn -ipv6 -kerberos -metalink -rtmp -samba -ssh -static-libs -test -threads ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32" CURL_SSL="openssl -axtls -gnutls -libressl -mbedtls -nss -polarssl -winssl" ELIBC="-Winnt")
```

**Comment by scorpp** [comment] 2016-06-07 17:05
Duplicate of #30, solution is here https://github.com/scorpp/db-vk/issues/30#issuecomment-139240267

In case you don't speak russian - you need to untick box 'Always use HTTPS' on VK.com settings page. Deadbeef's curl plugin is unable to stream over HTTPS

**Closed by scorpp** 2016-06-07 17:05 UTC
